### ISSUE TITLE
CRAN release?

### ISSUE THREAD

**Issue by jefferis** [r-lib/rappdirs#2]
I have a package that needs to download additional data. I'd like to use rappdirs as a dependency to choose a sensible location for that data, but I'd rather not have a non-CRAN dependency that requires compilation. Do you have any plans to submit this to CRAN? Is there a reason not to? Some alternative? Many thanks, Greg Jefferis.

**Comment by richfitz** [comment]
Anyone know if the "writing to disk" issue has a solution, or was an issue?  Does this need raising with CRAN on submission of packages that depend on rappdirs?

**Comment by gaborcsardi** [comment]
AFAIR `rappdirs` does not write to disk, actually. Packages that use it probably do, however.

**Comment by hadley** [comment]
The goal of rappdirs is to help people write to disk in the "correct" place
