### ISSUE TITLE
Windows: appname double in user_config_dir

### ISSUE THREAD

**Issue by surmann** [r-lib/rappdirs#23]
Hallo,

An appname is shown twice when I use `user_config_dir` on my windows system:

> packageVersion("rappdirs")
#[1] ‘0.3.1’
> rappdirs::user_config_dir("mypackage", expand = FALSE)
#[1] "C:\\\\Users\\\\name\\\\AppData\\\\Roaming\\\\mypackage\\\\mypackage"

My linux systems show it only once. Is this correct?

Thanks!

**Comment by trevorld** [comment]
Yes, this is the correct behaviour and is the same as the behaviour in the original python package: https://github.com/ActiveState/appdirs

Linux (and OSX) uses directory ``appname`` (ignoring any ``appauthor`` argument) while Windows uses directory ``appauthor\\appname`` and the function ``user_config_dir`` assigns ``appname`` as the default argument for ``appauthor``.  If you don't want the directory name to repeat then don't forget to set the "appauthor" argument in your function call i.e.:

    rappdirs::user_config_dir("mypackage", "packageauthor", expand = FALSE)
    #[1] "C:\\Users\\name\\AppData\\Roaming\\packageauthor\\mypackage"
