### ISSUE TITLE
user_data_dir under Mac

### ISSUE THREAD

**Issue by lgeistlinger** [r-lib/rappdirs#24]
I like `rappdirs::user_data_dir` for providing a general solution to storing package-associated data. 

However, I find the corresponding destination under Mac OS X

`~/Library/Application Support/<AppName>`

suboptimal - just due to the contained space.

https://superuser.com/questions/29111/what-technical-reasons-exist-for-not-using-space-characters-in-file-names

This seems to complicate things.

As an example:

```
data.dir <- rappdirs::user_data_dir()

html.file <- file.path(data.dir, "test.html")
content <- "<html>\n<body>\nHello World!\n</body>\n</html>"
writeLines(content, html.file)

# opens the browser in a terminal, but does nothing in RStudio
browseURL(html.file)

# works in RStudio, but not in a terminal anymore
html.file <- gsub(" ", "%20", html.file) 
browseURL(html.file)
```

What's the rationale behind choosing a file path with a space?

**Comment by gaborcsardi** [comment]
> ~/Library/Application Support/<AppName>
> suboptimal - just due to the contained space.

Well, that's the standard directory for user app data, chosen by Apple. There is not much we can do to change it.

As for your example, `browseURL` expects a URL, so it will have problems with other special characters as well, that cannot appear in URL. You can simply do 

```
URLencode(html.file)
```

before opening the URL.

**Comment by lgeistlinger** [comment]
```
URLencode(html.file)
```

seems to be equivalent to

```
gsub(" ", "%20", html.file)
```

in case of spaces and accordingly results in

```
The file /Users/<user>/Library/Application%20Support/test.html does not exist.
```

when running 

```
browseURL( URLencode(html.file) )
```

in a terminal.

**Comment by gaborcsardi** [comment]
That's a pity. I guess that's a bug in RStudio then, please report it at  https://github.com/rstudio/rstudio/issues. Thanks!
