### ISSUE TITLE
HTTP status was '404 Not Found'

### ISSUE THREAD

**Issue by EmilyKubicek** [r-lib/rappdirs#36]
Partial result when attempting to install devtools:

```
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/rappdirs_0.3.3.tgz'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/rappdirs_0.3.3.tgz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/rappdirs_0.3.3.tgz'
Warning in install.packages :
  download of package ‘rappdirs’ failed
```

After the recent update to this package, when downloading as a dependency for devtools, I am unable to do so. When manually following the link to 'https://cran.rstudio.com/bin/macosx/contrib/4.0/rappdirs_0.3.3.tgz' you can also see that it's not found.

**Comment by gaborcsardi** [comment]
This is a bug in CRAN, so we can't do much about it: 
https://stat.ethz.ch/pipermail/r-sig-mac/2021-January/013884.html

Use can use the canonical macOS CRAN machine as a workaround:
```r
install.packages("rappdirs", repos = c(CRAN = "https://mac.r-project.org/"))
```
