### ISSUE TITLE
Is there a way to make (force?) rappdirs::user_data_dir()to point to a local directory when app is deployed on Posit Connect? 

### ISSUE THREAD

**Issue by Shelmith-Kariuki** [r-lib/rappdirs#43]
Hi, 

We are building a shiny app that contains several inputs. When the user visits the app for the first time, we prompt them to save their inputs. The input file is saved in the directory provided by rappdirs::user_data_dir(). e.g in my machine (Mac), the file is saved in "~/Library/Application Support/xxx", xxx being the name of the folder. This works perfectly locally. 

Now when we deploy the app to Posit Connect, rappdirs::user_data_dir() registers a dir on the posit connect server such that another user can load that saved input file. Is there a way to tweak the function so that it points to the user's machine?

**Comment by gaborcsardi** [comment]
> Now when we deploy the app to Posit Connect, rappdirs::user_data_dir() registers a dir on the posit connect server such that another user can load that saved input file.

Are you sure about this? 

Aren't Connect deployments isolated from each other?

Also, what is that location? I _think_ the Connect server runs on Linux, where the default data directory should be inside your home directory. E.g. for me:
```r
> rappdirs::user_data_dir()
[1] "~/.local/share"
```

In any case, rappdirs follows the XDG spec (https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), so you can set the `XDG_DATA_HOME` env var to the desired location:
```r
> Sys.setenv("XDG_DATA_HOME" = "/tmp/")
> rappdirs::user_data_dir()
[1] "/tmp/"
```

**Comment by Shelmith-Kariuki** [comment]
@gaborcsardi , 

We are using the function to save an input file locally one people's machines, even though they are viewing a live deployed app. It's as though the file is being saved on the Connect server.

**Comment by gaborcsardi** [comment]
I don't really understand this. You cannot save a file in the user's machine if they are using your app through a web browser. You can offer them a file to download, but you cannot specify where it is saved. But maybe I am misunderstanding something.

**Comment by Shelmith-Kariuki** [comment]
No. Exactly that. I thought it was possible. Thanks a lot. I'll look for an alternative

**Comment by gaborcsardi** [comment]
If you want to store some (small amount of) data on the user's machine, then you can use cookies:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
There is also an R package for that:
https://r4ds.github.io/cookies/
(I haven't tried it, so this is not an endorsement.)
